version: "3.6"
services:
  pgDB:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: subly
      POSTGRES_DB: subly
volumes:
  db_data:
